# RHEL_VERSION defined in Makefile
FROM golang:1.19 AS builder
# smoke test to verify if golang is available
RUN go version

ARG PROJECT_VERSION=latest

COPY . /go/src/github.com/jtaleric/k8s-netperf/
WORKDIR /go/src/github.com/jtaleric/k8s-netperf/
RUN set -Eeux && \
    go mod download && \
    go mod verify

RUN GOOS=linux GOARCH=amd64 \
    go build \
    -trimpath \
    -ldflags="-w -s -X 'main.Version=${PROJECT_VERSION}'" \
    -o ./k8s-netperf cmd/k8s-netperf/k8s-netperf.go
RUN go test -cover -v ./...

ARG RHEL_VERSION
FROM registry.access.redhat.com/${RHEL_VERSION}:latest

COPY ./containers/appstream.repo /etc/yum.repos.d/centos8-appstream.repo

COPY ./containers/netperf.diff /tmp/netperf.diff
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && dnf clean all
RUN dnf install -y uperf && dnf clean all

RUN dnf install -y --nodocs make automake --enablerepo=centos9 --allowerasing  && \
    dnf install -y --nodocs gcc git bc lksctp-tools-devel texinfo --enablerepo=*

RUN git clone https://github.com/HewlettPackard/netperf
WORKDIR netperf

RUN git reset --hard 3bc455b23f901dae377ca0a558e1e32aa56b31c4 && \
    git apply /tmp/netperf.diff && \
    ./autogen.sh && \
    ./configure --enable-sctp=yes --enable-demo=yes && \
    make && make install

WORKDIR ../

RUN curl -L https://github.com/esnet/iperf/releases/download/3.16/iperf-3.16.tar.gz | tar xz && \
    cd iperf-3.16 && \
    ./configure; make install && \
    cd .. && \
    rm -rf iperf-3.16


RUN rm -rf netperf && \
    dnf clean all
COPY ./containers/super-netperf /usr/bin/super-netperf

COPY --from=builder /go/src/github.com/jtaleric/k8s-netperf/k8s-netperf /usr/bin/k8s-netperf
